# Generated by Django 2.1.5 on 2019-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20190202_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
