# Generated by Django 2.1.5 on 2019-02-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='text',
        ),
    ]
