# Generated by Django 2.1.7 on 2019-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20190215_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, to='files.FileTag'),
        ),
    ]
