# Generated by Django 2.1.7 on 2019-02-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20190215_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='filetag',
            name='slug',
            field=models.SlugField(default=123, max_length=48),
            preserve_default=False,
        ),
    ]
