# Generated by Django 2.1.7 on 2019-02-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20190215_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.FileTag'),
        ),
    ]
